### ISSUE TITLE
Integration eines Datenbankschemas

### ISSUE THREAD

**Issue by MPostler** [tuiSSE/lara-vedst#21]
könnte etwas schwieriger werden, wenn wir dynamische Spalten vergeben wollen (Ersteller der Umfrage wählt aus, wieviele Spalten er braucht)
für den Anfang sollte eine fixe Spaltenanzahl von z.B. 5 Spalten reichen

**Comment by ThomDietrich** [comment]
Dem Ansatz kann ich nicht ganz zustimmen. Es ist unklar wie viele Elemente eine Umfrage hat. Also warum nicht eine Tabelle für Umfragen und eine für Umfrage-Felder die dann wiederum die Umfrage-ID als ein Feld erhalten. Das lässt euch alle Freiheiten.
https://de.wikipedia.org/wiki/Normalisierung_%28Datenbank%29#Normalformen

**Comment by LudwigBr** [comment]
Nein, der Name ist nur ungünstig gewählt. Besser wäre "Integration eines Datenbankschemas".

**Comment by LudwigBr** [comment]
Ich habe noch einige Probleme beim Verständnis der aktuellen Userverwaltung.
In der aktuellen Tabelle "persons" befinden sich 4 Einträge (Max, Otto, Lena, THOR). Die User mit denen wir "zufällig" eingeloggt werden sind das allerdings nicht. Wo ist da die Verbindung?
Um das Problem zu konkretisieren: Ich würde die Umfrage oder wenigstens die Umfrageantworten mit den Usern verknüpfen, ich weiß aber nicht wie das bei der aktuellen Datenbankstruktur funktionieren soll, denn es gibt ja User die garnicht in der Datenbank auftauchen.
Ohne die Verbindung lässt sich nicht zuweisen wer bisher geantwortet hat und jeder User könnte x-Mal auf die gleiche Umfrage antworten + jede Umfrage wäre anonym.

**Comment by ThomDietrich** [comment]
Okay, das ist etwas missverständlich.
Die durch den Seeder erzeugten vier Nutzer (Max, ...) sind die die tatsächlich als Demo-Nutzer in der Datenbank stehen. https://github.com/tuiSSE/lara-vedst/blob/devel-poll/database/seeds/PersonsTableSeeder.php

Zusätzlich gibt es aber den zufällig-einloggen Workaround um keinen LDAP zu benötigen. Der dann zufällig eingeloggte Nutzer hat zwar keinen Datenbankeintrag aber er besitzt eine ID und eine Rolle. https://github.com/tuiSSE/lara-vedst/blob/devel-poll/app/Http/Controllers/LoginController.php#L105
Perfekte Lösung? Sicher nein. Ausreichend für euch, ich denke ja ;)

Was das Ausfüllen der Umfrage angeht: Ähnlich wie bei den Dienstplänen sollte ein eingeloggter Nutzer einfach als Name [Ich] auswählen können, alternativ sollte er aber auch einen fremden Namen tippen dürfen.
