### ISSUE TITLE
Monatsansicht Responsive

### ISSUE THREAD

**Issue by CAJan93** [tuiSSE/lara-vedst#36]
Eine der Dinge die wir (und Thomas!) als wichtig erachtet habe ist, dass unsere Anwendung auch mobil gut funktioniert. 

In diesem Issue wird versucht den Calendar responsive zu gestalten.

**Comment by ThomDietrich** [comment]
Das wäre auf jeden Fall mal ein netter Fix. Ich hatte mir das schon mal angesehen, was hältst du davon: Auf Smartphone-Displays wird der Event-Titel nicht angezeigt. Man sieht lediglich den Monatskalender, die farbigen Kästchen, das Event-Art Symbol (und die Startzeit?). Wenn man ein solches Element anklickt erhält man in Form eines Bootstrap Popovers alle weiteren Informationen und ein Link zum Öffnen des EIntrags.

**Comment by 4D44H** [comment]
Reference: [#68 - Rewrite month view for mobile - list of events instead of a table](https://github.com/4D44H/lara-vedst/issues/68)

**Comment by 4D44H** [comment]
Ein alternativer Vorschlag von mir war statt einer Tabelle eine Liste zu benutzen - für jeden Tag des Monats eine "Karteikarte" erstellen, sie in der Liste anzeigen - vertikal nacheinander, beim Laden der Seite zum Aktuellen Tag scrollen.
(Nur für kleine Bildschirme, ab iPad++ oder bei horizontal gehaltenem Smartphone wieder zur Tabelle wechseln, abfangen kann man das mit JavaScript.)

**Comment by LudwigBr** [comment]
Ein sehr schöner Fix, definitiv. Aber gerade im Bereich Frontend gibs auchnoch die ein oder andere Aufgabe mit "direkterem Umfragekontext", da sollte dann vielleicht vorher angesetzt werden?
Gerade in Hinblick auf die Abgabe nächsten Mittwoch sollte bis dahin der Prototyp fertig werden.

**Comment by 4D44H** [comment]
Sowas gehört eigentlich in die Kategorie "nice to have": Lara ist, vor allem, eine "Desktopanwendung", daher ist die Unterstützung von mobilen Geräten zwar stark gewünscht und soll eingeplant werden, aber paar Einschränkung dabei sind zu tolerieren. 
Meiner Meinung nach sollt ihr also erst alles rund um die Umfragen machen, und dann den Rest - falls die Zeit übrig bleibt. 
Spricht das aber mit Thomas ab - er kann euch bei der Abgrenzung von den Zielen des SWProjekts besser beraten ;)
