### ISSUE TITLE
Nutzer kann ein Freitextfeld ausfüllen und seine Eingabe speichern (10)

### ISSUE THREAD

**Issue by Laur1n** [tuiSSE/lara-vedst#41]

**Comment by LudwigBr** [comment]
Bisherige Implementierung passt noch nicht. Unser Modell geht aus von
1 Umfrage : N Fragen : N Antworten
deine Implementierung trifft eher:
1 Umfrage : 1 Frage : N Antworten

Meine Idee der Implementierung:
Darstellung der bisherigen Antworten in Tabellenform hier mal grob angedeutet:
![surveyanswer](https://cloud.githubusercontent.com/assets/18424338/15331996/32b44d22-1c64-11e6-8b1e-2f4e9f4ae2af.png)
Aber vermutlich gibs dann hier auch noch mehr Anhaltspunkte: #50

**Comment by ThomDietrich** [comment]
Ich denke auch dass die Darstellung in diese Richtung gehen sollte.
Schaut euch dazu bitte auch noch einmal die typischen Umfragen im Club-Umfeld an. Ich hatte euch dazu den Link zu einem Dienstplan (xxx.dp...) gegeben, hier findet Ihr aktuell eine ganze Reihe an Beispielen.
