### ISSUE TITLE
merge "responsive" and "q&a (including calender-poll)" into "merge-4D44H-changes"

### ISSUE THREAD

**Issue by LudwigBr** [tuiSSE/lara-vedst#56]
Ich bin dabei die Zweige wieder zusammenzuführen, bevor ich das in devel-poll übernehme ist aber noch ein bisschen was zu tun:  

responsive: @CAJan93
- wie schon privat besprochen existieren aktuell "calenderCellDate" und "monthCell" die prinzipiell den gleichen Zweck haben, d.h. davon wird nur eine benutzt

-> um Featureverlust zu vermeiden sollten die Änderungen aus calenderCellDate in monthCell übernommen werden

-> alternativ stell doch deine Bedenken hier einmal dar und markiere Maxim, dann wird er sich vermutlich recht fix melden

- "custom.css" scheint mir ein sehr unaussagekräftiger Name, vielleicht fällt dir da noch was besseres ein? ;)

calender-poll: @achim91 
- das Speichern der Umfrageantworten habe ich hier rausgenommen, u.a. weil es an der falschen Stelle war (wir hatten uns geeinigt einen neuen "halb-REST" Controller für SurveyAnswers mit den Methoden "store, update, delete" zu benutzen, um eine Implementierung kümmere ich mich schnellstmöglich, nachdem das mergen abgeschlossen ist und wir uns auf dem "richtigen" Zweig befinden)

- einen der hinzugefügten Views hab ich in dem Zuge auskommentieren müssen, da sie zwecks mangelnder Variablen nichtmehr funktioniert haben, auch die anderen neu hinzugefügten Views sollten auf Notwendigkeit geprüft werden

**Comment by ThomDietrich** [comment]
@achim91 zusätzlich hier vielleicht noch die Idee für den q&a branch nicht calendar-poll als base zu nutzen. Ludwig ist gerade dabei alles zu mergen und damit wieder eine etwas übersichtlichere Branch-Struktur zu ermöglichen. Der neue Stand von devel-poll (nach den merges) sollte ein besserer Ausgangspunkt für deinen Zweig sein. Den einen Commit den du aktuell schon hast kannst du dazu einfach per "cherry-pick" in einen neuen Branch überführen.

**Comment by LudwigBr** [comment]
Vermutlich war mein Ansatz nicht der beste, ich dachte wir kriegen die Probleme noch "schnell" vor dem Gesamtmerge behoben und könnten dann sauber weitermachen.
Mein neuer Ansatz, ich merge erstmal in devel-poll, so das wir dort zwar eine funktionierende, aber noch keine saubere Variante haben und öffne die Probleme einzeln als (Bug)Issues, alles was dann nicht direkt etwas mit dem Kalendar zu tun hat kann dann schon bearbeitet werden.

**Comment by CAJan93** [comment]
Du hast Recht @LudwigBr. Custom.css war wirklich kein guter Name!

custom.css ist nun monthViewResponsive.css
