### ISSUE TITLE
Kalenderfunktionen und responsive verbinden (calendarCellDate, monthCell)

### ISSUE THREAD

**Issue by LudwigBr** [tuiSSE/lara-vedst#57]

**Comment by LudwigBr** [comment]
Ich persönlich sehe keinen Grund für die "Umbenennung" von monthCell in calendarCellDate, das machts meiner Meinung nach nur weniger übersichtlich. Deshalb bin ich dafür deine responsive Änderungen in die monthCell einzupflegen und dann die calendarCellDate zu löschen.

**Comment by CAJan93** [comment]
Hi Ludwig, 
CalendarCellDate habe ich durchaus mit absicht angelegt. Der Grud war, dass ich monthCell ein Datum mit zurückliefert. Dieses Datum möchte ich aber sehr gerne an der Seite haben, was sich optisch einfach deutlich schöner macht. Darüber hinaus war ich mit den Styles von monthCell einfach nicht vertraut und es war deutlich einfacher bei 0 anzufangen, als zu versuchen die alten Styles "umzubauen". Ich werde deswegen an calendarCellDate festhalten. 
Vielleicht können wir ja monthCell löschen?

**Comment by LudwigBr** [comment]
Wenn die entsprechenden alten Funtkionen abgedeckt sind soll mir das natürlich auch egal sein.

**Comment by LudwigBr** [comment]
Bitte zieh Issues erst nach Done, wenn sie im devel-poll Zweig enthalten sind, ansonsten verlieren wir hier komplett die Übersicht.
