### ISSUE TITLE
create survey options unclear

### ISSUE THREAD

**Issue by ThomDietrich** [tuiSSE/lara-vedst#70]
Die Benennung der beiden Optionen "anonyme Umfrage" und "zeige Ergebnisse nach der Abstimmung" erklärt meiner Meinung nach nicht klar ihre Bedeutung. Die erste Option sollte nicht als Frage geschrieben sein.

Vorschlag:
* "nur für eingeloggte Nutzer sichtbar"
* "Ergebnisse sind erst nach dem Ausfüllen sichtbar"
* "Ergebnisse sind nur für den Umfragenersteller sichtbar"

**Comment by ThomDietrich** [comment]
Weiterhin: Würde es nicht besser aussehen, wenn Frage und Fragetyp jeweils in einer Zeile stehen würden?

**Comment by MPostler** [comment]
Mit der Bennenung der Optionen hast du vollkommen recht. Wenn man schon die ganze Zeit mit den Variablen im Hintergrund arbeitet, vergisst man, dass der Nutzer ihre genaue Bedeutung gar nicht weiß. @achim91 - willst du das in deinem aktuellen Zweig ändern?

Bei dem Treffen mit Maxim gestern ist es uns auch aufgefallen, dass wir bisher ziemlich viel an den linken Rand geklatscht haben. Aktueller Plan ist, die Checkbox für erforderlich rechts neben "Frage #..." zu setzen und den Fragetyp auch rechts neben einem vergrößerten Feld für den Text der Frage anzuzeigen. @achim91 kann da vermutlich mehr darüber sagen.

**Comment by MPostler** [comment]
Ich hab die Benennungen jetzt in createSurvey#4-poll geändert. Sollte beim Mergen also in devel-poll landen.
