### ISSUE TITLE
SQL Fehler bei der Umfrage-Erstellung

### ISSUE THREAD

**Issue by ThomDietrich** [tuiSSE/lara-vedst#71]
Ich habe versucht eine Umfrage zu erstellen. Sie sollte drei Fragen enthalten, die erste ist "Name" und dabei scheint es direkt zu einem Fehler zu kommen:
```sql
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'survey_id' cannot be null (SQL: insert into `survey_questions` (`survey_id`, `order`, `field_type`, `is_required`, `question`, `updated_at`, `created_at`) values (, 0, 1, 1, Name, 2016-06-15 13:06:16, 2016-06-15 13:06:16))
```

**Comment by ThomDietrich** [comment]
Mögliche Erklärung: die Eingabe des Datums hat Probleme gemacht und deswegen wurde die Survey nicht erstellt. Wieso bekomme ich dann aber keinen Fehler dazu?

**Comment by MPostler** [comment]
Das Problem ist durch einen schnellen (ungetesteten) Bugfix von mir heute früh entstanden. Im Controller wurde die Survey bisher immer erst gespeichert und dann nachgeschaut, ob auch Fragen vorhanden sind. Wenn hier nun alle Fragen leer gelassen wurden, wurde zwar die Umfrage schon gespeichert, allerdings ohne zugehörige Fragen. Ich wollte das Problem heute früh dadurch lösen, dass ich die Umfrage erst speichere, wenn die Fragen abgehandelt wurden.

Die Fehlermeldung beruht darauf, dass die ID der Umfrage noch nicht existent ist, als sie einer Frage zugeordnet werden soll (da die Umfrage zu dem Zeitpunkt noch nicht gespeichert war). Daher die Fehlermeldung, dass survey_id nicht null sein kann. Ich hab meinen Bugfix von heute früh reverted, das Problem sollte also nicht mehr auftreten. Wir müssen jetzt nur in Kauf nehmen, dass Nutzer jetzt mehr oder weniger versehentlich Umfragen ohne zugehörige Fragen erstellen können.

**Comment by MPostler** [comment]
Eventuell finde ich dafür aber noch eine schönere Lösung, wie man die obigen Eingaben bei der Umfrage behalten kann, wenn man nur leere Fragen eingibt - ohne die Umfrage in der Datenbank zu speichern.
